config/routes.rb
Ecommerce::Application.routes.draw do

  get "list/show"
  get "list/add"
  get "list/remove"
  get 'signup', to: 'users#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'

  get 'logout', to: 'sessions#destroy', as: 'logout'

  get "myproducts/index"

  get "myproducts/add"

  get "myproducts/remove"

  resources :users

  resources :shops

  resources :skus

  resources :products
  
  resources :sessions

  get '/:action', controller: :report
  
  root 'skus#index'
  

  

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :products
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shop }
      else
        format.html { render action: 'new' }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :link, :image_url)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.haml
= form_for @shop do |f|
  - if @shop.errors.any?
    #error_explanation
      %h2= "#{pluralize(@shop.errors.count, "error")} prohibited this shop from being saved:"
      %ul
        - @shop.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :link
    = f.text_field :link
  .field
    = f.label :image_url
    = f.text_field :image_url
  .actions
    = f.submit 'Save'

app/views/shops/edit.html.haml
%h1 Editing shop

= render 'form'

= link_to 'Show', @shop
\|
= link_to 'Back', shops_path

app/views/shops/index.html.haml
%h1 Listing shops

%table
  %tr
    %th Name
    %th Link
    %th Image url
    %th free shipping
    %th free shipping from
    %th shipping min price
    %th reviews count
    %th review score
  - @shops.each do |shop|
    %tr
      %td= shop.name
      %td= shop.link
      %td
        %img{src: shop.image_url}
      %td= shop.free_shipping
      %td= shop.free_shipping_from
      %td= shop.shipping_min_price
      %td= shop.reviews_count
      %td= shop.review_score
      %td= link_to 'Show', shop
      %td= link_to 'Edit', edit_shop_path(shop)
      %td= link_to 'Destroy', shop, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Shop', new_shop_path

app/views/shops/new.html.haml
%h1 New shop

= render 'form'

= link_to 'Back', shops_path

app/views/shops/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @shop.name
%p
  %b Link:
  = @shop.link
%p
  %b Image url:
  = @shop.image_url

= link_to 'Edit', edit_shop_path(@shop)
\|
= link_to 'Back', shops_path