config/routes.rb
Ecommerce::Application.routes.draw do

  get "list/show"
  get "list/add"
  get "list/remove"
  get 'signup', to: 'users#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'

  get 'logout', to: 'sessions#destroy', as: 'logout'

  get "myproducts/index"

  get "myproducts/add"

  get "myproducts/remove"

  resources :users

  resources :shops

  resources :skus

  resources :products
  
  resources :sessions

  get '/:action', controller: :report
  
  root 'skus#index'
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
has_secure_password
has_and_belongs_to_many :skus
has_many :products, through: :skus
has_many :shops, through: :products

# Αλγόριθμος επιλογής προϊόντων με βάση τη διαθεσιμότητα
def fastest_products
  
  # Αρχικοποίηση μεταβλητής όπου θα αποθηκευθούν τα προϊόντα 
  fastest_products = []
  
  skus.each do |sku|
    # έλεγχος για το αν κάποιο προίόν δεν υπάρχει
    unless sku.fastest_product.nil?
      # εισαγωγή του προϊόντος με την καλύτερη
      # διαθεσιμότητα στο array fastest_products.
      fastest_products.push(sku.fastest_product)
    end 
  end
  
  # επιστροφή array με τα προϊόντα με τη
  # καλύτερη διαθεσιμότητα
  return fastest_products
end

# Υπολογισμός του κόστους των προϊόντων που έχει επιλέξει ο
# αλγόριθμος επιλογής προϊόντων με βάση τη διαθεσιμότητα
def fastest_products_cost
  cost = 0
  #ap fastest_products
  fastest_products.each{ |product| cost += product.price }
  return cost
end

# Αλγόριθμος επιλογής προϊόντων με βάση τη τιμή
def cheapest_products

  # Αρχικοποίηση μεταβλητής όπου θα αποθηκευθούν τα προϊόντα 
  cheapest_products = []
  
  skus.each do |sku|
    # έλεγχος για το αν κάποιο προίόν δεν υπάρχει
    unless sku.cheapest_product.nil?
      # εισαγωγή του προϊόντος με την καλύτερη τιμή
      # στο array cheapest_products.
      cheapest_products.push(sku.cheapest_product) 
    end
  end
  
  # επιστροφή array με τα προϊόντα με τη καλύτερη τιμή
  return cheapest_products
end

# Υπολογισμός του κόστους των προϊόντων που έχει επιλέξει ο
# αλγόριθμος επιλογής προϊόντων με βάση τη τιμή
def cheapest_products_cost
  cost = 0
  cheapest_products.each{ |product| cost += product.price }
  return cost
end

# Αλγόριθμος επιλογής προϊόντων με βάση τα καταστήματα
def common_shop_products
  
  # Αρχικοποίηση μεταβλητής όπου θα αποθηκευθούν τα προϊόντα 
  products_list = []
  
  # Αρχικοποίηση βοηθητικής μεταβλητής μετρητή καταστημάτων
  shops_count = Hash.new(0)
  
  # Επαναληπτική δομή που δημιουργει μια κατάσταση με τα
  # καταστήματα στα οποία περιέχεται ο μεγαλύτερος αριθμός
  # προϊόντων που έχει βάλει ο χρήστης στη λίστα του
  skus.each do |sku|
    sku.shops.uniq.each do |shop|
      shops_count[shop] += 1
    end
  end
  
  # Ταξινόμηση της παραπάνω κατάστασης.
  # Τα καταστήματα με τα περισσότερα προϊόντα
  # βρίσκονται στην αρχή του array 
  shops_list = shops_count.to_a.sort do |x,y|
    y[1] <=> x[1]
  end
  
  # Από το array εξάγουμε τη στήλη με τα ονόματα των
  # καταστημάτων οπότε τώρα το array shops_list περιέχει
  # μια ταξινομημένη λίστα με καταστήματα 
  shops_list.collect!{|x| x[0]}
  
  skus.each do |sku|
    
    # η μεταβλητή product περιέχει ένα προϊόν του οποίου
    # το κατάστημα βρίσκεται υψηλότερα στη λίστα
    # καταστημάτων shops_list
    product= sku.product_by_shop(shops_list)
    
    # έλεγχος για το αν κάποιο προίόν δεν υπάρχει
    unless product.nil?
      # εισαγωγή του προϊόντος στο array products_list.
      products_list.push(product)
    end
  end
  
  # επιστροφή array με τα προϊόντα
  return products_list 
end

# Υπολογισμός του κόστους των προϊόντων που έχει επιλέξει ο
# αλγόριθμος επιλογής προϊόντων με βάση τα καταστήματα
def common_shop_products_cost
  cost = 0
  common_shop_products.each{ |product| cost += product.price }
  return cost
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @fastest_products = @user.fastest_products
    @cheapest_products = @user.cheapest_products
    @common_shop_products = @user.common_shop_products
    @fastest_products_cost = @user.fastest_products_cost
    @cheapest_products_cost = @user.cheapest_products_cost
    @common_shop_products_cost = @user.common_shop_products_cost
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :full_name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :full_name
    = f.text_field :full_name
  .field
    = f.label :password_digest
    = f.text_field :password_digest
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Full name
    %th Password digest
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.full_name
      %td= user.password_digest
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%p#notice= notice

%h1 Εγγραφή
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  %table.credentials
    %tr
      %td
        = f.label :Όνομα_χρήστη
      %td
        = f.text_field :name
      %td
        δώστε το όνομα χρήστη (username)
    %tr
      %td
        = f.label :Ολόκληρο_όνομα
      %td
        = f.text_field :full_name
      %td
        δώστε το όνομά σας 
    %tr
      %td
        = f.label :Κωδικός
      %td
        = f.password_field :password
      %td
    %tr
      %td
        = f.label :Επιβεβαίωση_κωδικού
      %td
        = f.password_field :password_confirmation
      %td
    %tr
      %td
      %td
        = f.submit 'Εγγραφή'
      %td

app/views/users/show.html.haml
%h1 Επιθεώρηση προϊόντων μου

/ O users_controller μας δίνει τις μεταβλητές fastest_products, cheapest_products και common_shop_products

%h2 Διαθεσιμότητα
%p.explain Επιλογή καταστημάτων με κριτήριο πρώτα τη διαθεσιμότητά τους και μετά την τιμή.
/ καλεί το partial _products.html.haml από τα views των products με παράμετρο τον πίνακα @fastests_products
= render partial: "products/products", locals: {products: @fastest_products}
%p.cost
  Το κόστος είναι:
  %span #{'%.2f' % @fastest_products_cost}€
%hr.products
%h2 Φτηνότερα
%p.explain Επιλογή καταστημάτων με κριτήριο την τιμή τους.
= render partial: "products/products", locals: {products: @cheapest_products}
%p.cost
  Το κόστος είναι:
  %span #{'%.2f' % @cheapest_products_cost}€
%hr.products
%h2 Μικρότερος αριθμός καταστημάτων
%p.explain Επιλογή καταστημάτων με κριτήριο το να επιλεχθούν λιγότερα καταστήματα.
= render partial: "products/products", locals: {products: @common_shop_products}
%p.cost
  Το κόστος είναι:
  %span #{'%.2f' % @common_shop_products_cost}€
    