config/routes.rb
Ecommerce::Application.routes.draw do

  get "list/show"
  get "list/add"
  get "list/remove"
  get 'signup', to: 'users#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'

  get 'logout', to: 'sessions#destroy', as: 'logout'

  get "myproducts/index"

  get "myproducts/add"

  get "myproducts/remove"

  resources :users

  resources :shops

  resources :skus

  resources :products
  
  resources :sessions

  get '/:action', controller: :report
  
  root 'skus#index'
  

  

end

app/models/sku.rb
class Sku < ActiveRecord::Base
  has_many :products
  has_many :shops, through: :products
  
  @@access_token=ENV['SKROUTZ']
  
  def self.fetch(sku_id)
    #begin
      json = JSON.parse(`curl -s -XGET https://api.skroutz.gr/skus/#{sku_id} -H 'Accept: application/vnd.skroutz+json; version=3' -H 'Authorization: #{@@access_token}'`)
      if json.has_key?('error')
        raise "error contacting skroutz: #{json['error']}"
      end
      #ap json
      sku = Sku.create(
        name: json['sku']['name'] ,
        price_max: json['sku']['price_max'] ,
        price_min: json['sku']['price_min'] ,
        image: json['sku']['images']['main'])
        
      puts "#{sku_id}\t#{json['sku']['name']}"
      json = JSON.parse(`curl -s -XGET https://api.skroutz.gr/skus/#{sku_id}/products -H 'Accept: application/vnd.skroutz+json; version=3' -H 'Authorization: #{@@access_token}'`)
      
      #ap json["products"]
      json["products"].each do |product|
      puts "product"
      #ap product
      
      unless Shop.exists?(skroutz_id:  product["shop_id"])
        puts "create shop"
        ap shop_json = JSON.parse(`curl -s -XGET https://api.skroutz.gr/shops/#{product["shop_id"]} -H 'Accept: application/vnd.skroutz+json; version=3' -H 'Authorization: #{@@access_token}'`)
        
        
        Shop.create(name:               shop_json["shop"]["name"],
                    skroutz_id:         shop_json["shop"]["id"],
                    link:               shop_json["shop"]["link"],
                    image_url:          shop_json["shop"]["image_url"],
                    free_shipping:      shop_json['shop']['shipping']["free"],
                    free_shipping_from: shop_json['shop']['shipping']["free_from"],
                    shipping_min_price: shop_json['shop']['shipping']["min_price"],
                    reviews_count:      shop_json['shop']["reviews_count"],
                    review_score:       shop_json['shop']["review_score"]
                   )
      end
      shop = Shop.find_by skroutz_id: product["shop_id"]
      sku.products.push(
        Product.create( name: product["name"],
                        availability: product["availability"],
                        price: product["price"],
                        shop: shop))
      end
      
      return sku
    #rescue
    #  return nil
    #end
  end
  
# Αλγόριθμος επιλογής προϊόντος με βάση τη διαθεσιμότητά του
def fastest_product

  # Αρχικοποίηση μεταβλητής όπου θα αποθηκευθούν τα προϊόντα
  fastest_products = []
  
  # Τα δεδομένα που προέρχονται από το skroutz και αφορούν τη
  # διαθεσιμότητα των προϊόντων έχουν τις εξής δυνατές τιμές:
  # • Σε απόθεμα
  # • 1 έως 3 ημέρες
  # • 4 έως 7 ημέρες
  # • 7+ ημερες
  # • Κατόπιν Παραγγελίας
  # • nil (χωρίς τιμή)
  #
  # Αυτές οι τιμές είναι σε μορφή κειμένου και βρίσκονται
  # στη μεταβλητή possible_availabilities
  possible_availabilities = ["Σε απόθεμα",
                             "1 έως 3 ημέρες",
                             "4 έως 7 ημέρες",
                             "7+ ημερες",
                             "Κατόπιν Παραγγελίας",
                             nil]
  
  # Με μια δομή επανάληψης επιλέγουμε πρώτα τα στοιχεία που
  # έχουν availability "σε απόθεμα". Αυτά τα στοιχεία τα
  # ταξινομούμε με βάση την τιμή τους και τα εισάγουμε στη
  # μεταβλητή cheapest_products μετά κάνουμε το ίδιο για τα
  # στοιχεία που έχουν availability "1 έως 3 ημέρες"
  # και ούτω καθεξής.
  
  # για κάθε τιμή availability
  possible_availabilities.each do |availability|
    
    # H συνάρτηση select είναι μια συνάρτηση που έχει η δομή
    # Array της Ruby και χρησιμοποιείται για να φιλτράρουμε
    # τα στοιχεία ενός Array. Στην περίπτωσή μας φιλτράρουμε
    # τα στοιχεία του Array products με βάση την τιμή
    # availability που έχουν. Τα στοιχεία που τηρούν αυτό
    # τον έλεγχο τα αποθηκεύουμε προσωρινά στην μεταβλητή tmp
    tmp = products.select do |p|
      p.availability == availability
    end
    
    # H συνάρτηση sort είναι μια συνάρτηση που έχει η δομή
    # Array της Ruby και χρησιμοποιείται για να ταξινομήσουμε
    # τα στοιχεία του array που θέλουμε με βάση κάποια τιμή
    # που έχουν. Στην περίπτωσή μας ταξινομούμε τα στοιχεία
    # του Array tmp με βάση την τιμή που έχουν. Τo
    # ταξινομημένο array αποθηκεύεται πάλι στη μεταβλητή tmp
    tmp.sort! do |x,y|
      y[:price] <=> x[:price]
    end
    
    # αντιστροφή του array tmp ώστε τα φθηνότερα
    # προϊόντα να πάνε πρώτα
    tmp.reverse!
    
    # Τέλος το array tmp συνενώνεται στο τέλος του
    # array fastest_products
    fastest_products += tmp
  end
  
  # H συνάρτηση επιστρέφει το πρώτο προϊόν από το array
  # fastest_products που περιέχει τα προϊόντα που πρωτίστως
  # βρίσκονται σε διαθεσιμότητα και δευτερευόντως
  # έχουν χαμηλότερη τιμή.
  return fastest_products.first
end


# Αλγόριθμος επιλογής φθηνότερου προϊόντος
def cheapest_product
  
  # ταξινόμηση των προϊόντων με βάση την τιμή τους και
  # ανάθεση του ταξινομημένου array στην μεταβλητή tmp
  tmp = products.sort do |x,y|
    y[:price] <=> x[:price]
  end
  
  # το τελευταίο στοιχείο του array είναι και το φθηνότερο
  # οπότε επέστρεψε αυτό
  return tmp.last
end


# Αλγόριθμος επιλογής προϊόντος με βάση το κατάστημα
#
# ο αλγόριθμος δέχεται σαν όρισμα μια ταξινομημένη λίστα
# με τα καταστήματα από τα οποία θα προτιμούσαμε να αγοράσουμε
# το προϊόν. Και επιστρέφει το προϊόν που βρίσκεται στο
# κατάστημα υψηλότερης προτίμησης
def product_by_shop (shops_list)
  shops_list.each do |shop|
    products.each do |product|
      if product.shop == shop
        return product
      end
    end
  end
  return nil
end

end

app/controllers/skus_controller.rb
class SkusController < ApplicationController
  before_action :set_sku, only: [:show, :edit, :update, :destroy]

  # GET /skus
  # GET /skus.json
  def index
    @skus = Sku.all
    @userskus = []
    if current_user
      @userskus = current_user.skus
    end
  end

  # GET /skus/1
  # GET /skus/1.json
  def show
  end

  # GET /skus/new
  def new
    @sku = Sku.new
  end

  # GET /skus/1/edit
  def edit
  end

  # POST /skus
  # POST /skus.json
  def create
    ap @sku = Sku.fetch(sku_id_param)

    respond_to do |format|
      unless @sku.nil?
        puts "hello".green
        format.html { redirect_to @sku, notice: 'Sku was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sku }
      else
        format.html { redirect_to '/skus/new', notice: 'Sku was not created maybe Skroutz credentials have expired or you entered a wrong id' }
        format.json { render json: @sku.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skus/1
  # PATCH/PUT /skus/1.json
  def update
    respond_to do |format|
      if @sku.update(sku_params)
        format.html { redirect_to @sku, notice: 'Sku was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sku.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skus/1
  # DELETE /skus/1.json
  def destroy
    @sku.destroy
    respond_to do |format|
      format.html { redirect_to skus_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sku
      @sku = Sku.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sku_params
      params.require(:sku).permit(:name, :price_max, :price_min, :image)
    end
    
    def sku_id_param
      params.require(:sku_id)
    end
end

app/helpers/skus_helper.rb
module SkusHelper
end

app/views/skus/_big_list.html.haml
%ul
  - skus.each do |sku|
    %li{id: "sku#{sku.id}"}
      %p.name= sku.name
      .img-container
        %img{src: sku.image}
        /%img{src: 'image.svg'}
      %p prices from #{sku.price_min}€ to #{sku.price_max}€
      -if current_user
        -unless userskus.include?(sku)
          %a.button{href: "/list/add/?id=#{sku.id}"} add to cart
        -else
          %a.remove.button{href: "/list/remove/?id=#{sku.id}"} remove from cart

app/views/skus/_form.html.haml
= form_for @sku do |f|
  - if @sku.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sku.errors.count, "error")} prohibited this sku from being saved:"
      %ul
        - @sku.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price_max
    = f.text_field :price_max
  .field
    = f.label :price_min
    = f.text_field :price_min
  .field
    = f.label :image
    = f.text_field :image
  .actions
    = f.submit 'Save'

app/views/skus/_small_list.html.haml
%table
  - userskus.each do |sku|
    %tr
      %td.image
        %img{src: sku.image, height: '50'}
      %td.name
        =sku.name
    %tr
      %td.button
        %a.remove.button{href: "/list/remove/?id=#{sku.id}"} remove
      %td.price #{sku.price_min}€ - #{sku.price_max}€
%a.inspect{href: "/users/#{current_user.id}"} επισκόπηση

app/views/skus/edit.html.haml
%h1 Editing sku

= render 'form'

= link_to 'Show', @sku
\|
= link_to 'Back', skus_path

app/views/skus/index.html.haml
%h1 Προϊόντα
%table.grid
  %tr
    %td.skus
      = render partial: "big_list", locals: {skus: @skus, userskus: @userskus}
    %td.userskus
      %p.caption τα προϊόντα μου
      -if current_user && !@userskus.empty?
        = render partial: "small_list", locals: {skus: @skus, userskus: @userskus}
      -elsif current_user && @userskus.empty?
        %p.no-products προσθέστε προϊόντα
      -else
        %p.no-products συνδεθείτε ή εγγραφείτε για να προσθέσετε προϊόντα
    
.modal

app/views/skus/new.html.haml
%h1 Εισαγωγή προϊόντων
-flash.each do |key, value|
  %p.center.alert
    =value
%p.center δώστε τοv κωδικό που χρησιμοποιεί το Skroutz για αυτό το  Sku
= form_tag("/skus", method: "post") do
  %table.credentials
    %tr
      %td
        = label_tag :Κωδικός_SKU
      %td
        = text_field_tag :sku_id
    %tr
      %td
      %td
        = submit_tag 'Εισαγωγή'
      %td

app/views/skus/show.html.haml
%p#notice.center= notice
%h2.center
  =@sku.name
%p.center
  %b Price max:
  #{@sku.price_max}€
%p.center
  %b Price min:
  #{@sku.price_min}€

= render partial: "products/products", locals: {products: @sku.products}