config/routes.rb
Ecommerce::Application.routes.draw do

  get "list/show"
  get "list/add"
  get "list/remove"
  get 'signup', to: 'users#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'

  get 'logout', to: 'sessions#destroy', as: 'logout'

  get "myproducts/index"

  get "myproducts/add"

  get "myproducts/remove"

  resources :users

  resources :shops

  resources :skus

  resources :products
  
  resources :sessions

  get '/:action', controller: :report
  
  root 'skus#index'
  

  

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :sku
  belongs_to :shop
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :sku_id, :shop_id, :availability, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def shops_products_hash (products)
    shops = {}
    products.each do |product|
      shops[product.shop] = [] unless shops[product.shop]
      shops[product.shop].push product
    end
    return shops
  end
end

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :sku
    = f.text_field :sku
  .field
    = f.label :shop
    = f.text_field :shop
  .field
    = f.label :availability
    = f.text_field :availability
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = f.submit 'Save'

app/views/products/_products.html.haml
%table.products
  %tr
    %th Κατάστημα
    %th Προϊόν
    %th Διαθεσιμότητα
    %th Τιμή
  - shops_products_hash(products).each do |shop, products|
    %tr.shop
      %td.shop{rowspan: products.size}
        = shop.name
        %br
        %br
        %img.shop{src: shop.image_url}
        %br
        -if shop.shipping_min_price
          %p.shop
            ελάχιστα
            μεταφορικά
            #{shop.shipping_min_price}€
        -if shop.free_shipping and shop.free_shipping_from
          %p.shop
            δωρεάν
            μεταφορικά
            από #{shop.free_shipping_from}€
        -if shop.reviews_count and shop.review_score
          %p.shop
            #{shop.reviews_count} άτομα το βαθμολογούν με #{shop.review_score}
      -sum = 0
      -products.each_with_index do |product, index|
        -sum += product.price
        -if index > 0
          %tr.product
            %td.name
              =product.name
              %br
              %br
                %img{src: product.sku.image}
            %td.availability #{product.availability}
            %td.price #{'%.2f' % product.price}€
        -else
          %td.name
            =product.name
            %br
            %br
              %img{src: product.sku.image}
          %td.availability #{product.availability}
          %td.price  #{'%.2f' % product.price}€
      %tr.sum
        %td.sum-caption{colspan:3} σύνολο:&nbsp;&nbsp;&nbsp;
        %td.sum-price #{'%.2f' % sum}€


-# %table.products
-#   - products.each do |product|
-#     %tr
-#       %td.image-cell
-#         %img{src: product.sku.image}
-#       %td
-#         %table.product
-#           %caption= product.name
-#           %tr
-#             %th κατάστημα:
-#             %td
-#               %p.shop
-#                 %img.shop{src: product.shop.image_url}
-#                 = product.shop.name
-#           %tr
-#             %th διαθεσιμότητα:
-#             %td
-#               %p= product.availability
-#           %tr
-#             %th τιμή:
-#             %td
-#               %p #{product.price}€

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Listing products

= render partial: "products", locals: {products: @products}

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product.name
%p
  %b Sku:
  = @product.sku
%p
  %b Shop:
  = @product.shop
%p
  %b Availability:
  = @product.availability
%p
  %b Price:
  = @product.price

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path